name: Build and Deploy Next.js App

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t my-nextjs-app .
        docker run -d -p 3000:3000 my-nextjs-app

